version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Paris
    open-pull-requests-limit: 2
    labels:
      - dependabot
