FROM node:12-alpine

WORKDIR /app

COPY ./packages/server ./packages/server
COPY ./package.json .
COPY ./yarn.lock .

RUN yarn install
RUN yarn server build

EXPOSE 8000

CMD ["yarn","server","start"]
