name: Automerge

on:
  pull_request:
    branches:
      - master
    paths:
      - '!packages/**'
      - '!package.json'
  push:
    branches:
      - master
    paths:
      - '!packages/**'
      - '!package.json'

jobs:
  dummy-test-client:
    name: Test the client
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  dummy-build-server:
    name: Build the server
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
