name: Validate client

on:
  pull_request:
    branches:
      - master
    paths:
      - "packages/client/**"
      - "package.json"
  push:
    branches:
      - master
    paths:
      - "packages/client/**"
      - "package.json"

jobs:
  dummy-build-server:
    name: Build the server
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  test:
    name: Test the client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn client test
